server:
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:user-key-store.jks
    key-store-password: secret
    key-alias: user-server
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:user-trust-store.jks
    trust-store-password: secret
    trust-store-type: JKS