server:
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:proxy-key-store.jks
    key-store-password: secret
    key-alias: client
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:proxy-trust-store.jks
    trust-store-password: secret
    trust-store-type: JKS